import http from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import { createHash, randomUUID } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
await mkdir(path.join(root, 'data'), { recursive: true });
const db = new DatabaseSync(path.join(root, 'data', 'workflow.sqlite'));
db.exec(`PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, email TEXT NOT NULL, display_name TEXT NOT NULL, role TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS matters(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', privilege_label INTEGER NOT NULL, work_product_label INTEGER NOT NULL, self_analysis_label INTEGER NOT NULL, created_by TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS matter_members(matter_id TEXT NOT NULL, user_id TEXT NOT NULL, PRIMARY KEY(matter_id,user_id));
CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, matter_id TEXT NOT NULL, title TEXT NOT NULL, instructions TEXT NOT NULL, assignee_id TEXT, due_at TEXT, status TEXT NOT NULL, created_by TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, matter_id TEXT NOT NULL, author_id TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_events(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, matter_id TEXT, task_id TEXT, actor_id TEXT NOT NULL, event_type TEXT NOT NULL, source TEXT NOT NULL, payload TEXT NOT NULL, occurred_at TEXT NOT NULL, previous_hash TEXT NOT NULL, event_hash TEXT NOT NULL UNIQUE);`);

const ids = { tenant: 'tenant-demo', attorney: 'user-attorney', user: 'user-business', auditor: 'user-auditor' };
if (!db.prepare('SELECT id FROM tenants WHERE id=?').get(ids.tenant)) {
  db.prepare('INSERT INTO tenants VALUES (?,?)').run(ids.tenant, 'Northwind Claims');
  for (const [id, email, name, role] of [[ids.attorney, 'amaya.chen@northwind.test', 'Amaya Chen', 'attorney'], [ids.user, 'jordan.lee@northwind.test', 'Jordan Lee', 'business_user'], [ids.auditor, 'auditor@northwind.test', 'Morgan Hall', 'auditor']]) db.prepare('INSERT INTO users VALUES (?,?,?,?,?)').run(id, ids.tenant, email, name, role);
}
const json = (res, code, body) => { res.writeHead(code, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type, X-User-Id' }); res.end(JSON.stringify(body)); };
const now = () => new Date().toISOString();
function user(req) { const id = req.headers['x-user-id'] || ids.attorney; return db.prepare('SELECT * FROM users WHERE id=?').get(id); }
function allowed(actor, matterId) { if (!actor || actor.role === 'platform_admin' || actor.role === 'tenant_admin' || actor.role === 'auditor') return !!actor; return !!db.prepare('SELECT 1 FROM matter_members WHERE matter_id=? AND user_id=?').get(matterId, actor.id); }
function writeAudit({ tenantId, matterId = null, taskId = null, actor, eventType, source, payload = {} }) { const previous = db.prepare('SELECT event_hash FROM audit_events WHERE tenant_id=? ORDER BY occurred_at DESC, id DESC LIMIT 1').get(tenantId)?.event_hash || 'GENESIS'; const occurredAt = now(), id = randomUUID(); const canonical = JSON.stringify({ id, tenantId, matterId, taskId, actorId: actor.id, eventType, source, payload, occurredAt, previous }); const hash = createHash('sha256').update(canonical).digest('hex'); db.prepare('INSERT INTO audit_events VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id, tenantId, matterId, taskId, actor.id, eventType, source, JSON.stringify(payload), occurredAt, previous, hash); return { id, hash }; }
async function body(req) { let raw = ''; for await (const chunk of req) raw += chunk; try { return raw ? JSON.parse(raw) : {} } catch { throw Error('Invalid JSON'); } }
function requireRole(actor, ...roles) { return actor && roles.includes(actor.role); }

const api = async (req, res) => {
  if (req.method === 'OPTIONS') return json(res, 204, {}); const url = new URL(req.url, 'http://localhost'); const actor = user(req); if (!actor) return json(res, 401, { error: 'Unknown user' });
  if (req.method === 'GET' && url.pathname === '/api/bootstrap') { const matters = db.prepare(`SELECT m.* FROM matters m WHERE m.tenant_id=? AND (? IN ('platform_admin','tenant_admin','auditor') OR EXISTS(SELECT 1 FROM matter_members mm WHERE mm.matter_id=m.id AND mm.user_id=?)) ORDER BY m.created_at DESC`).all(actor.tenant_id, actor.role, actor.id); return json(res, 200, { actor, users: db.prepare('SELECT id,display_name,role FROM users WHERE tenant_id=?').all(actor.tenant_id), matters }); }
  if (req.method === 'POST' && url.pathname === '/api/matters') { if (!requireRole(actor, 'attorney', 'tenant_admin')) return json(res, 403, { error: 'Only attorneys may create matters' }); const b = await body(req), id = randomUUID(); if (!b.title?.trim()) return json(res, 400, { error: 'Title is required' }); const memberIds = (b.memberIds || []).filter(memberId => db.prepare('SELECT 1 FROM users WHERE id=? AND tenant_id=?').get(memberId, actor.tenant_id)); db.prepare('INSERT INTO matters VALUES (?,?,?,?,?,?,?,?,?)').run(id, actor.tenant_id, b.title.trim(), b.description || '', +!!b.privilegeLabel, +!!b.workProductLabel, +!!b.selfAnalysisLabel, actor.id, now()); db.prepare('INSERT INTO matter_members VALUES (?,?)').run(id, actor.id); for (const memberId of memberIds) db.prepare('INSERT OR IGNORE INTO matter_members VALUES (?,?)').run(id, memberId); writeAudit({ tenantId: actor.tenant_id, matterId: id, actor, eventType: 'matter.created', source: 'web', payload: { title: b.title } }); return json(res, 201, { id }); }
  const matterMatch = url.pathname.match(/^\/api\/matters\/([^/]+)$/); if (req.method === 'GET' && matterMatch) { const matter = db.prepare('SELECT * FROM matters WHERE id=? AND tenant_id=?').get(matterMatch[1], actor.tenant_id); if (!matter || !allowed(actor, matter.id)) return json(res, 404, { error: 'Matter not found' }); const tasks = db.prepare('SELECT t.*, u.display_name assignee_name FROM tasks t LEFT JOIN users u ON u.id=t.assignee_id WHERE t.matter_id=? ORDER BY t.updated_at DESC').all(matter.id); const messages = db.prepare('SELECT ms.*, u.display_name author_name FROM messages ms JOIN users u ON u.id=ms.author_id WHERE ms.matter_id=? ORDER BY ms.created_at').all(matter.id); const events = db.prepare('SELECT ae.*,u.display_name actor_name FROM audit_events ae JOIN users u ON u.id=ae.actor_id WHERE ae.matter_id=? ORDER BY ae.occurred_at DESC,ae.id DESC').all(matter.id).map(e => ({ ...e, payload: JSON.parse(e.payload) })); return json(res, 200, { matter, tasks, messages, events }); }
  const taskRoute = url.pathname.match(/^\/api\/matters\/([^/]+)\/tasks$/); if (req.method === 'POST' && taskRoute) { const matterId = taskRoute[1], matter = db.prepare('SELECT id FROM matters WHERE id=? AND tenant_id=?').get(taskRoute[1], actor.tenant_id); if (!matter || !allowed(actor, matterId) || !requireRole(actor, 'attorney', 'tenant_admin')) return json(res, 403, { error: 'Only matter attorneys may assign tasks' }); const b = await body(req), id = randomUUID(), assignee = db.prepare('SELECT id FROM users WHERE id=? AND tenant_id=?').get(b.assigneeId, actor.tenant_id); if (!b.title?.trim()) return json(res, 400, { error: 'Task title is required' }); db.prepare('INSERT INTO tasks VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id, actor.tenant_id, matterId, b.title.trim(), b.instructions || '', assignee?.id || null, b.dueAt || null, 'open', actor.id, now(), now()); writeAudit({ tenantId: actor.tenant_id, matterId, taskId: id, actor, eventType: 'task.created', source: 'web', payload: { title: b.title, assigneeId: assignee?.id || null } }); return json(res, 201, { id }); }
  const messageRoute = url.pathname.match(/^\/api\/matters\/([^/]+)\/messages$/); if (req.method === 'POST' && messageRoute) { const matterId = messageRoute[1], matter = db.prepare('SELECT id FROM matters WHERE id=? AND tenant_id=?').get(messageRoute[1], actor.tenant_id); if (!matter || !allowed(actor, matterId)) return json(res, 403, { error: 'No matter access' }); const b = await body(req), id = randomUUID(); if (!b.body?.trim()) return json(res, 400, { error: 'Message cannot be empty' }); db.prepare('INSERT INTO messages VALUES (?,?,?,?,?,?)').run(id, actor.tenant_id, matterId, actor.id, b.body.trim(), now()); writeAudit({ tenantId: actor.tenant_id, matterId, actor, eventType: 'message.sent', source: 'web', payload: { messageId: id } }); return json(res, 201, { id }); }
  const taskUpdate = url.pathname.match(/^\/api\/tasks\/([^/]+)$/); if (req.method === 'PATCH' && taskUpdate) { const task = db.prepare('SELECT * FROM tasks WHERE id=? AND tenant_id=?').get(taskUpdate[1], actor.tenant_id); if (!task || !allowed(actor, task.matter_id)) return json(res, 404, { error: 'Task not found' }); const b = await body(req), status = b.status; const permitted = ['open', 'in_progress', 'submitted', 'changes_requested', 'closed']; if (!permitted.includes(status)) return json(res, 400, { error: 'Invalid status' }); const attorneyAction = ['changes_requested', 'closed'].includes(status); if (attorneyAction && !requireRole(actor, 'attorney', 'tenant_admin')) return json(res, 403, { error: 'Attorney review required' }); if (!attorneyAction && task.assignee_id !== actor.id && !requireRole(actor, 'attorney', 'tenant_admin')) return json(res, 403, { error: 'Only assignee may update task' }); db.prepare('UPDATE tasks SET status=?,updated_at=? WHERE id=?').run(status, now(), task.id); writeAudit({ tenantId: actor.tenant_id, matterId: task.matter_id, taskId: task.id, actor, eventType: `task.${status}`, source: 'web', payload: { note: b.note || '' } }); return json(res, 200, { ok: true }); }
  if (req.method === 'POST' && url.pathname === '/api/extension/events') { const b = await body(req), task = db.prepare('SELECT * FROM tasks WHERE id=? AND tenant_id=?').get(b.taskId, actor.tenant_id); if (!task || task.assignee_id !== actor.id || !allowed(actor, task.matter_id)) return json(res, 403, { error: 'Select a task assigned to you' }); const actions = ['opened', 'updated', 'reviewed', 'submitted', 'completed']; if (!actions.includes(b.action)) return json(res, 400, { error: 'Invalid declared action' }); const destination = String(b.destination || '').slice(0, 512); const recordRef = String(b.recordRef || '').slice(0, 256); writeAudit({ tenantId: actor.tenant_id, matterId: task.matter_id, taskId: task.id, actor, eventType: `activity.${b.action}`, source: b.connector === 'axon' ? 'extension.axon' : 'extension.generic', payload: { destination, recordRef, attestation: String(b.attestation || '').slice(0, 1000) } }); return json(res, 201, { ok: true }); }
  return json(res, 404, { error: 'Not found' });
};
const server = http.createServer(async (req, res) => { try { if (req.url.startsWith('/api/')) return await api(req, res); const file = req.url === '/' ? 'index.html' : req.url.slice(1); if (!/^[\w.-]+$/.test(file)) throw Error('Not found'); const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css' }; const text = await readFile(path.join(root, 'public', file)); res.writeHead(200, { 'Content-Type': types[path.extname(file)] || 'text/plain' }); res.end(text); } catch (e) { json(res, e.message === 'Not found' ? 404 : 500, { error: e.message }); } });
server.listen(process.env.PORT || 3000, () => console.log(`Privileged Matter Workflow listening on http://localhost:${process.env.PORT || 3000}`));
